path: C:\Users\Chris\Desktop\pdf_discovery
train: data/train/images
val: data/val/images
test: data/test/images

# Classes
names:
  0: table
  1: finance

# yolo task=detect mode=train model="foduucom/table-detection-and-extraction" data="config.yaml" epochs=50 imgsz=640 batch=8